/**
 * The News API
 *
 * ...
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param message 
 * @param code 
 */
@Serializable
data class Error (

    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "code") @Required val code: kotlin.Int

)

