/**
 * The News API
 *
 * ...
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param uuid 
 * @param title 
 * @param description 
 * @param url 
 * @param source 
 * @param imageUrl 
 * @param language 
 * @param publishedAt 
 * @param categories 
 */
@Serializable
data class NewsInfo (

    @SerialName(value = "uuid") @Required val uuid: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "source") @Required val source: kotlin.String,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "language") val language: kotlin.String? = null,

    @SerialName(value = "published_at") val publishedAt: kotlin.String? = null,

    @SerialName(value = "categories") val categories: kotlin.collections.List<kotlin.String>? = null

)

