/**
 * The News API
 *
 * ...
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Meta
import org.openapitools.client.models.NewsInfo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param meta 
 * @param `data` 
 */
@Serializable
data class NewsAllGet200Response (

    @SerialName(value = "meta") val meta: Meta? = null,

    @SerialName(value = "data") val `data`: kotlin.collections.List<NewsInfo>? = null

)

